spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Diogo0104!
    url: jdbc:mysql://localhost:3306/turisgo_bd?serverTimeZone=UTC


  flyway:
    enabled: false

  application:
    name: bdd